### ISSUE TITLE
Publication question

### ISSUE THREAD

**Issue by andreped** [st084331/Automatic_Steatosis_Recognition#6]
Hello! I am the developer of the [livermask](https://github.com/andreped/livermask) tool.

Just noticed that it may seem that you have used it in this project.
Is this project linked to any journal publication or preprint?

If so, it would be great to add it to the growing list of livermask journal applications (see [here](https://github.com/andreped/livermask#applications-of-livermask)).

**Comment by akabynda** [comment]
Hello, the article has not been published yet.  I will let you know as soon as this happens.Отправлено с устройства Galaxy
-------- Исходное сообщение --------От: André Pedersen ***@***.***> Дата: 02.06.2023  13:53  (GMT+03:00) Кому: st084331/Automatic_Steatosis_Recognition ***@***.***> Копия: Subscribed ***@***.***> Тема: [st084331/Automatic_Steatosis_Recognition] Publication question (Issue #6) 
Hello! I am the developer of the livermask tool.
Just noticed that it may seem that you have used it in this project.
Is this project linked to any journal publication or preprint?
If so, it would be great to add it to the growing list of livermask journal applications (see here).

**Comment by andreped** [comment]
I found a recent paper that cited the livermask tool, which I added to the [Applications list](https://github.com/andreped/livermask#applications-of-livermask) in the README. I|m therefore closing this issue.

I assume it is your paper. If not, please let me know otherwise.
